name: Build
on:
  workflow_dispatch:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: mrndstvndv/buildozer-action@v320a33e
        id: buildozer
        with:
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/myapp-0.1-arm64-v8a-debug.apk
