name: Build
on:
  workflow_dispatch:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5.4.0
        with:
          pyproject-file: "$GITHUB_WORKSPACE/master/pyproject.toml"

      - name: Build for android
        working-directory: "$GITHUB_WORKSPACE/master"
        run: |
          ls $GITHUB_WORKSPACE
          uv sync
          uv run buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
