name: Build
on:
  workflow_dispatch:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5.4.0

      - name: Setup java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Buildozer reqirements
        run: |
          sudo apt-get update -y
          sudo apt-get -y install aidl zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 libffi-dev
          
      - name: Build for android
        run: |
          ls $GITHUB_WORKSPACE/master
          cd "$GITHUB_WORKSPACE/master"
          pwd
          uv sync
          uv run buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
